### ISSUE TITLE
Division error

### ISSUE THREAD

**Issue by m312z** [bluescarni/piranha#106]
There seems to have been a breaking change in a recent update. Given the following:

pexpr x = pexpr hasht{"x"}
pexpr y = x / x;

I now see the error:

> terminate called after throwing an instance of 'std::invalid_argument'
>   what():  
> function: dispatch_binary_div
> where: /usr/local/include/piranha/series.hpp, 844
> what: divisor in series division does not consist of a single coefficient

(https://github.com/KCL-Planning/SMTPlan/tree/master/SMTPlan depends upon Piranha, and used this kind of expression.)

**Comment by bluescarni** [comment]
Thanks for the report!

The polynomial division/gcd functionality was removed from Piranha starting some time after the release of version 0.10. The main reason was that trying to maintain those functionalities to an adequate level of performance turned out to be a massive time sink (especially the gcd parts), and, since Piranha is still a one-man effort, I made the decision to ditch those functionalities for now to re-focus on the core capabilities of Piranha.

Do you need true multivariate polynomial division for your application, or some limited form of it? The current Piranha version can still deal with Laurent polynomials, so the snippet you quoted can be written in another form as:

```
pexpr y = x * math::pow(x,-1);
```

It is my intention to re-visit division (but not gcd) in the (hopefully near) future. In the meantime, you can keep on using piranha version 0.10, which you can download from the release page:

https://github.com/bluescarni/piranha/releases

I am also open to maintaining a branch based on 0.10 for bugfixes etc. if needed.

Let me know what works best for you.

**Comment by m312z** [comment]
Thanks for the really fast response!

I've made the change you suggested and our code seems to work with the most recent version. Thanks for the help.

Best Regards,
Michael

P.S. You can find our code here:
https://github.com/KCL-Planning/SMTPlan/tree/master/SMTPlan
http://kcl-planning.github.io/SMTPlan/

**Comment by bluescarni** [comment]
@m312z Thanks for the links, it's always interesting to know what piranha is used for. Would you mind if I add links to SMTPlan in the piranha documentation?

I am closing the report as it seems to be solved.

**Comment by m312z** [comment]
@bluescarni Of course, feel free to add some links.

Thanks again,
Michael
