### ISSUE TITLE
Piranha compilation fails with AppleClang

### ISSUE THREAD

**Issue by isuruf** [bluescarni/piranha#89]
Is this not supported anymore?

**Comment by bluescarni** [comment]
@isuruf any pointer to the failure? It worked a few weeks ago when we interacted with the Spack dev, I might have broken something in the meantime.

I have not set up travis for OSX, evidently it needs to be done otherwise the risk of random breakage is too high.

**Comment by isuruf** [comment]
Here's a log, https://travis-ci.org/isuruf/staged-recipes/builds/175048650#L673-L695

**Comment by isuruf** [comment]
This is with v0.6.

v0.5 builds fine, although pyranha fails with a thread-local unsupported failure, https://travis-ci.org/isuruf/staged-recipes/builds/175376116#L649-L661

**Comment by isuruf** [comment]
It would be a good idea to setup travis for OSX. In symengine, we are trying to use conda for the dependencies, so that the CI setup is almost identical for OSX and Linux, symengine/symengine#1119

**Comment by bluescarni** [comment]
I don't understand what is going on. Here:

https://travis-ci.org/isuruf/staged-recipes/builds/175048650#L553

It tests if the ``thread_local`` keyword is available via a ``try_compile``, and that succeeds. The test program being compiled is:

https://github.com/bluescarni/piranha/blob/master/cmake_modules/yacma/yacma_thread_local_tests.cpp

I am wondering if this simple tests program compiles because the ``thread_local`` variable is a POD type?

I can try to modify it in a branch to see if that's the issue, would you then be able to test it out? Otherwise I can hardcode to just disable ``thread_local`` for OSX but that would be a bit suckish.

**Comment by bluescarni** [comment]
@isuruf It might also be possible that the ``try_compile`` compiles with a set of flags different from the subsequent build. Do you have any idea on how I could debug that? Some online C++ compiler maybe?

**Comment by bluescarni** [comment]
@isuruf I am going to disable ``thread_local`` on OSX unconditionally for now, see #90. Can you test this one? It's just a single commit on top of version 0.6.

**Comment by isuruf** [comment]
@bluescarni, here's the log, https://travis-ci.org/isuruf/piranha/jobs/175424463#L1089-L1090

You can play with OSX in travis with this, https://github.com/isuruf/piranha/tree/travis
Btw, clang in xcode6.4 works fine, but clang in xcode6.1 doesn't

**Comment by isuruf** [comment]
Fixed with #91
